### PR TITLE
v1.16.3

### PR DESCRIPTION
**Pull request by willgarrett64**

### CODE REVIEW

**Review by adamkdean — APPROVED** [review]

**Comment by adamkdean** [comment]
@willgarrett64 on narrower screens, there isn't much we can do, but it was truncating on full width which was an issue.

**Comment by willgarrett64** [comment]
@adamkdean no problem. What you could do is set the column width in pixels instead of % to the exact amount you need to not truncate, and then set the remaining columns in %. That's what I did for dates I believe

**Comment by adamkdean** [comment]
Perhaps but there will always be some truncation somewhere. An alternative is to put `title` attributes onto things so there is a tooltip.

**Comment by willgarrett64** [comment]
@adamkdean good thinking, I'll add that. My general approach with all these tables has been to truncate hash/address/etc, and leave columns like date, status, amount, etc with no truncation.

**Pull request merged**
